// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	ErrCode int64  `json:"err_code"`
	ErrMsg  string `json:"err_msg"`
}

type AddReq struct {
	Book  string `form:"book"`
	Price int64  `form:"price"`
}

type AddResp struct {
	BaseResp
	Data AddData `json:"data"`
}

type AddData struct {
	Ok bool `json:"ok"`
}

type CheckReq struct {
	Book string `form:"book"`
}

type CheckResp struct {
	BaseResp
	Data CheckData `json:"data"`
}

type CheckData struct {
	Found bool  `json:"found"`
	Price int64 `json:"price"`
}
